-- Add CARGOS
IF NOT EXISTS(SELECT * FROM preciso_administracion_cargos WHERE id_cargo = 1) BEGIN INSERT INTO preciso_administracion_cargos (nombre_cargo) VALUES ('Gerente') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cargos WHERE id_cargo = 2) BEGIN INSERT INTO preciso_administracion_cargos (nombre_cargo) VALUES ('Profesional Especializado') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cargos WHERE id_cargo = 3) BEGIN INSERT INTO preciso_administracion_cargos (nombre_cargo) VALUES ('Profesional') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cargos WHERE id_cargo = 4) BEGIN INSERT INTO preciso_administracion_cargos (nombre_cargo) VALUES ('Analista') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cargos WHERE id_cargo = 5) BEGIN INSERT INTO preciso_administracion_cargos (nombre_cargo) VALUES ('Ingeniero') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cargos WHERE id_cargo = 6) BEGIN INSERT INTO preciso_administracion_cargos (nombre_cargo) VALUES ('Consultor') END

-- Add PAISES
IF NOT EXISTS(SELECT * FROM nexco_paises WHERE id_pais = 1) BEGIN INSERT INTO nexco_paises (nombre_pais, sigla_pais) VALUES ('Colombia', 'CO') END
IF NOT EXISTS(SELECT * FROM nexco_paises WHERE id_pais = 2) BEGIN INSERT INTO nexco_paises (nombre_pais, sigla_pais) VALUES ('España', 'ES') END
IF NOT EXISTS(SELECT * FROM nexco_paises WHERE id_pais = 3) BEGIN INSERT INTO nexco_paises (nombre_pais, sigla_pais) VALUES ('Estados Unidos', 'US') END

-- Add DIVISAS
IF NOT EXISTS(SELECT * FROM nexco_divisas WHERE id_divisa = 1) BEGIN INSERT INTO nexco_divisas (nombre_divisa, sigla_divisa) VALUES ('Peso Colombiano', 'COP') END
IF NOT EXISTS(SELECT * FROM nexco_divisas WHERE id_divisa = 2) BEGIN INSERT INTO nexco_divisas (nombre_divisa, sigla_divisa) VALUES ('Euro', 'EUR') END
IF NOT EXISTS(SELECT * FROM nexco_divisas WHERE id_divisa = 3) BEGIN INSERT INTO nexco_divisas (nombre_divisa, sigla_divisa) VALUES ('Dolar', 'USD') END

-- Add SISTEMAS FUENTE
IF NOT EXISTS(SELECT * FROM nexco_sistema_fuente WHERE id_sf = 1) BEGIN INSERT INTO nexco_sistema_fuente (nombre_sf, sigla_sf, festivo, id_pais, activo) VALUES ('Dialogo', 'DIA', 1, 1, 1) END
IF NOT EXISTS(SELECT * FROM nexco_sistema_fuente WHERE id_sf = 2) BEGIN INSERT INTO nexco_sistema_fuente (nombre_sf, sigla_sf, festivo, id_pais, activo) VALUES ('Bank Trade', 'EY0', 0, 1, 0) END
IF NOT EXISTS(SELECT * FROM nexco_sistema_fuente WHERE id_sf = 3) BEGIN INSERT INTO nexco_sistema_fuente (nombre_sf, sigla_sf, festivo, id_pais, activo) VALUES ('Extranjera', 'GA0', 1, 2, 1) END


-- Add TIPOS EVENTOS
IF NOT EXISTS(SELECT * FROM nexco_tipo_evento WHERE id_tipo_evento = 1) BEGIN INSERT INTO nexco_tipo_evento (nombre_tipo_evento) VALUES ('Conciliación') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_evento WHERE id_tipo_evento = 2) BEGIN INSERT INTO nexco_tipo_evento (nombre_tipo_evento) VALUES ('Notas') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_evento WHERE id_tipo_evento = 3) BEGIN INSERT INTO nexco_tipo_evento (nombre_tipo_evento) VALUES ('Resultados') END

-- Add TIPO DOCUMENTO
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 1) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('ACCIONISTA','Z') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 2) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('CARNET DIPLOMATICO','A') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 3) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('PERMISO PERMANENCIA TERMPORAL','V') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 4) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIP','0') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 5) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('CEDULA DE CIUDADANIA','1') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 6) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('CEDULA EXTRANJERIA','2') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 7) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIT PERSONA JURIDICA(NACIONAL)','3') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 8) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('TARJETA DE IDENTIDAD','4') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 9) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('PASAPORTE','5') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 10) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIT EXTRANJERIA','6') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 11) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('SOC. EXTRANJERAS SIN NIT','7') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 12) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('IDENT FIDEICOMISO','8') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_tipo_documento WHERE id_tipo_documento = 13) BEGIN INSERT INTO preciso_administracion_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIT PARA PERSONAS NATURALES','9') END

-- IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI') BEGIN INSERT INTO preciso_administracion_usuarios(centro,contra,correo,creacion,empresa,estado,primer_nombre,password_token,codigo_usuario) VALUES ('0000','$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin@admin.com',GETDATE(),'0013',1,'Administrador Nexco',NULL,'NEXADMI') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin@admin.com',GETDATE(),'Pilar','Maritza','Llantoy','Sanchez',NULL,'NEXADMI','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI1') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin1@admin.com',GETDATE(),'Maria','Maritza','Llantoy','Sanchez',NULL,'NEXADMI1','2000-01-28','2000-01-28','2000-01-28',1,78945612,2) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI2') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin2@admin.com',GETDATE(),'Juana','Maritza','Llantoy','Sanchez',NULL,'NEXADMI2','2000-01-28','2000-01-28','2000-01-28',1,78945612,2) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI3') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin3@admin.com',GETDATE(),'Elizabeth','Maritza','Llantoy','Sanchez',NULL,'NEXADMI3','2000-01-28','2000-01-28','2000-01-28',1,78945612,4) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI4') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin4@admin.com',GETDATE(),'Carla','Maritza','Llantoy','Sanchez',NULL,'NEXADMI4','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI5') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin5@admin.com',GETDATE(),'Pia','Maritza','Llantoy','Sanchez',NULL,'NEXADMI5','2000-01-28','2000-01-28','2000-01-28',1,78945612,3) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI6') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin6@admin.com',GETDATE(),'Lucia','Maritza','Llantoy','Sanchez',NULL,'NEXADMI6','2000-01-28','2000-01-28','2000-01-28',1,78945612,5) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI7') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin7@admin.com',GETDATE(),'Valeria','Maritza','Llantoy','Sanchez',NULL,'NEXADMI7','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI8') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin8@admin.com',GETDATE(),'Carolina','Maritza','Llantoy','Sanchez',NULL,'NEXADMI8','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI9') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin9@admin.com',GETDATE(),'Julio','Mario','Llantoy','Sanchez',NULL,'NEXADMI9','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI10') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin10@admin.com',GETDATE(),'Pedro','Mario','Llantoy','Sanchez',NULL,'NEXADMI10','2000-01-28','2000-01-28','2000-01-28',1,78945612,2) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI11') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin11@admin.com',GETDATE(),'Jorge','Mario','Llantoy','Sanchez',NULL,'NEXADMI11','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI12') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin12@admin.com',GETDATE(),'Lucio','Mario','Llantoy','Sanchez',NULL,'NEXADMI12','2000-01-28','2000-01-28','2000-01-28',1,78945612,4) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_usuarios WHERE codigo_usuario='NEXADMI13') BEGIN INSERT INTO preciso_administracion_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin13@admin.com',GETDATE(),'Carlos','Mario','Llantoy','Sanchez',NULL,'NEXADMI13','2000-01-28','2000-01-28','2000-01-28',1,78945612,6) END


IF NOT EXISTS(SELECT * FROM preciso_administracion_perfiles WHERE nombre_perfil = 'ADMIN') BEGIN INSERT INTO preciso_administracion_perfiles ( nombre_perfil) VALUES ('ADMIN')END
IF NOT EXISTS(SELECT * FROM preciso_administracion_perfiles WHERE nombre_perfil = 'USER') BEGIN INSERT INTO preciso_administracion_perfiles ( nombre_perfil) VALUES ('USER') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_perfiles WHERE nombre_perfil = 'RESPONSABLE') BEGIN INSERT INTO preciso_administracion_perfiles ( nombre_perfil) VALUES ('RESPONSABLE') END

-- Add views to the database
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Usuarios') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Usuarios','/admin/users',1,'Administración','Usuarios','NA') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Roles') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Roles','/profile/roles',1,'Administración','Roles','NA') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Cargos') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cargos','/admin/cargos',1,'Administración','Cargos','NA') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Países') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Países','/parametry/countries',1,'Parametría','Parametros Generales','Países') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Tipos Eventos') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Tipos Eventos','/parametry/eventType',1,'Parametría','Parametros Generales','Tipos Eventos') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Divisas') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Divisas','/parametry/currency',1,'Parametría','Parametros Generales','Divisas') END
IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Sistemas Fuentes') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Sistemas Fuentes','/parametry/sourceSystem',1,'Parametría','Parametros Generales','Sistemas Fuentes') END

--IF NOT EXISTS(SELECT * FROM preciso_administracion_vistas WHERE nombre = 'Ver Tipos Eventos') BEGIN INSERT INTO preciso_administracion_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Tipos Eventos','/parametry/typeEvent',1,'Parametría','Parametros Generales','Tipos Eventos') END

IF NOT EXISTS(SELECT * FROM nexco_parametros_pyg WHERE id_parametros_pyg = 1) BEGIN INSERT INTO nexco_parametros_pyg (aplica_reversion) VALUES (0) END


-- Add JOBS
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 1) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (1,'GOF Base Fiscal',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 2) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (2,'HADT140',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 3) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (3,'Query',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 4) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (4,'SICC',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 5) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (5,'Depositos',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 6) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (6,'CONDETARI',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 7) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (7,'Desconnv15',0) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_cuadro_mando_jobs WHERE id_job = 8) BEGIN INSERT INTO preciso_administracion_cuadro_mando_jobs (id_job, nombre, estado) VALUES (8,'Calculo 1%',0) END

IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 1 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (1,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 2 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (2,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 3 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (3,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 4 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (4,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 5 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (5,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 6 AND id_perfil=2) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (6,2) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 7 AND id_perfil=2) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (7,2) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 8 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (8,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 9 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (9,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 10 AND id_perfil=3) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (10,3) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 11 AND id_perfil=3) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (11,3) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 12 AND id_perfil=3) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (12,3) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 13 AND id_perfil=1) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (13,1) END
IF NOT EXISTS(SELECT * FROM preciso_administracion_user_rol WHERE id_usuario = 14 AND id_perfil=2) BEGIN INSERT INTO preciso_administracion_user_rol (id_usuario,id_perfil) VALUES (14,2) END

-- IF NOT EXISTS(SELECT * FROM preciso_administracion_rol_vista AS nrv, preciso_administracion_vistas AS nv WHERE nrv.id_perfil = 1 AND nv.nombre = 'Ver Cuadro Mando Intergrupo' AND nv.id_vista = nrv.id_vista) BEGIN INSERT INTO preciso_administracion_rol_vista (id_perfil,id_vista) VALUES (1,4) END
--IF NOT EXISTS(SELECT * FROM preciso_administracion_rol_vista AS nrv, preciso_administracion_vistas AS nv WHERE nrv.id_perfil = 1 AND nv.nombre = 'Ver Roles' AND nv.id_vista = nrv.id_vista) BEGIN INSERT INTO preciso_administracion_rol_vista (id_perfil,id_vista) VALUES (1,4) END

IF NOT EXISTS(SELECT * FROM preciso_administracion_rol_vista AS nrv, preciso_administracion_vistas AS nv WHERE nrv.id_perfil = 1 AND nv.nombre = 'Ver Roles' AND nv.id_vista = nrv.id_vista) BEGIN INSERT INTO preciso_administracion_rol_vista (id_perfil,id_vista, p_modificar, p_visualizar) VALUES (1,(SELECT id_vista FROM preciso_administracion_vistas WHERE nombre = 'Ver Roles'),1,1) END

IF NOT EXISTS(SELECT * FROM nexco_operacion_riesgo WHERE cuenta_local='-') BEGIN INSERT INTO nexco_operacion_riesgo (cuenta_local) VALUES ('-') END

-- Datos predeterminados para Contrapartida y Contratos genericos
IF NOT EXISTS(SELECT NULL FROM nexco_counterparty_generic_contracts) BEGIN INSERT INTO nexco_counterparty_generic_contracts (concepto, cuenta, contrato, fuente_informacion,saldo) VALUES (' 2-DESCONT_DESC_CONCIL','196095999','001302039000000101', 'Diferencias conciliación',-1), ('1-DESCONT_CTAS_MANUALES','196095999','001302039000000102','Manuales (Anexos 8)',-1), ('1-DESCONTAB_PROV_GENERAL','196095999','001302039000000103','Provisión general Capitales',-1), ('1-DESCONTAB_PROV_GENERICA_INTERESES','196095999','001302039000000103','Provisión general Intereses',-1), ('2-DESCONT_SIN_SCOPE','196095999','001302039000000104','Rechazos descontabilización',1), ('1-DESCONT_CTAS_RENTA_FIJA','196095999','001302039000000105','Anexos 8 - Renta fija',-1) END

-- Datos predeterminados para Arbol Decisión Segmentos FINREP
IF NOT EXISTS(SELECT NULL FROM nexco_arbol_decision_segmento) BEGIN INSERT INTO nexco_arbol_decision_segmento (codigo_ifrs9, descripcion_sectorizacion, corasu_op, corasu, sub_corasu_op, sub_corasu, ciiu_op, ciiu, numero_empleados_op, numero_empleados, total_activos_op, total_activos, total_ventas_op, total_ventas, verificacion_contratos, otros_criterios) VALUES ('001','Bancos Centrales','=','G','=','00','','','','','','','','','',''), ('002','Administraciones Públicas','=','G','<>','00','','','','','','','','','',''), ('003','Entidades de Crédito','=','M','IN','20,21,22,23,24,25,26','=','6412','','','','','','','',''), ('004','Otras instituciones financieras','=','M','IN','21,22,23,24,25,26','IN','CIIU','','','','','','','',''), ('005','Sociedades no Financieras Mayoristas','=','M','IN','00,01,10,12','','','>','250','>','50000000','>','43000000','','Que cumpla los criterios de sociedad no financiera'), ('005','Sociedades no Financieras Mayoristas','=','M','=','20','<>','6412','>','250','>','50000000','>','43000000','','Que cumpla los criterios de sociedad no financiera'), ('005','Sociedades no Financieras Mayoristas','=','M','IN','21,22,23,24,25,26','NOT IN','CIIU','>','250','>','50000000','>','43000000','','Que cumpla los criterios de sociedad no financiera'), ('006','Sociedades no Financieras Minorista','=','M','IN','00,01,10,12','','','','','','','','','','Sociedades no Financieras no Mayoristas'), ('006','Sociedades no Financieras Minorista','=','M','=','20','<>','6412','','','','','','','','Sociedades no Financieras no Mayoristas'), ('006','Sociedades no Financieras Minorista','=','M','IN','21,22,23,24,25,26','NOT IN','CIIU','','','','','','','','Sociedades no Financieras no Mayoristas'), ('007','Hogares','=','F','IN','00,10','=','10','','','','','','','',''), ('007','Hogares','=','F','','','','','','','','','','','Tiene producto(s) de Libranza',''), ('007','Hogares','=','F','','','','','','','','','','','Tiene producto(s) de Adelanto de Nómina',''), ('007','Hogares','=','F','=','17','','','','','','','','','',''), ('008','Autónomos','=','F','','','','','','','','','','','','No incluidas en hogares') END
