-- Add CARGOS
IF NOT EXISTS(SELECT * FROM nexco_cargos WHERE id_cargo = 1) BEGIN INSERT INTO nexco_cargos (nombre_cargo) VALUES ('Gerente') END
IF NOT EXISTS(SELECT * FROM nexco_cargos WHERE id_cargo = 2) BEGIN INSERT INTO nexco_cargos (nombre_cargo) VALUES ('Profesional Especializado') END
IF NOT EXISTS(SELECT * FROM nexco_cargos WHERE id_cargo = 3) BEGIN INSERT INTO nexco_cargos (nombre_cargo) VALUES ('Profesional') END
IF NOT EXISTS(SELECT * FROM nexco_cargos WHERE id_cargo = 4) BEGIN INSERT INTO nexco_cargos (nombre_cargo) VALUES ('Analista') END
IF NOT EXISTS(SELECT * FROM nexco_cargos WHERE id_cargo = 5) BEGIN INSERT INTO nexco_cargos (nombre_cargo) VALUES ('Ingeniero') END
IF NOT EXISTS(SELECT * FROM nexco_cargos WHERE id_cargo = 6) BEGIN INSERT INTO nexco_cargos (nombre_cargo) VALUES ('Consultor') END

-- Add PAISES
IF NOT EXISTS(SELECT * FROM nexco_paises WHERE id_pais = 1) BEGIN INSERT INTO nexco_paises (nombre_pais, sigla_pais) VALUES ('Colombia', 'CO') END
IF NOT EXISTS(SELECT * FROM nexco_paises WHERE id_pais = 2) BEGIN INSERT INTO nexco_paises (nombre_pais, sigla_pais) VALUES ('España', 'ES') END
IF NOT EXISTS(SELECT * FROM nexco_paises WHERE id_pais = 3) BEGIN INSERT INTO nexco_paises (nombre_pais, sigla_pais) VALUES ('Estados Unidos', 'US') END

-- Add TIPO DOCUMENTO
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 1) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('ACCIONISTA','Z') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 2) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('CARNET DIPLOMATICO','A') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 3) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('PERMISO PERMANENCIA TERMPORAL','V') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 4) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIP','0') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 5) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('CEDULA DE CIUDADANIA','1') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 6) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('CEDULA EXTRANJERIA','2') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 7) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIT PERSONA JURIDICA(NACIONAL)','3') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 8) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('TARJETA DE IDENTIDAD','4') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 9) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('PASAPORTE','5') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 10) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIT EXTRANJERIA','6') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 11) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('SOC. EXTRANJERAS SIN NIT','7') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 12) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('IDENT FIDEICOMISO','8') END
IF NOT EXISTS(SELECT * FROM nexco_tipo_documento WHERE id_tipo_documento = 13) BEGIN INSERT INTO nexco_tipo_documento (nombre_tipo_documento,codigo_tipo_documento) VALUES ('NIT PARA PERSONAS NATURALES','9') END

-- IF NOT EXISTS(SELECT * FROM nexco_usuarios WHERE codigo_usuario='NEXADMI') BEGIN INSERT INTO nexco_usuarios(centro,contra,correo,creacion,empresa,estado,primer_nombre,password_token,codigo_usuario) VALUES ('0000','$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin@admin.com',GETDATE(),'0013',1,'Administrador Nexco',NULL,'NEXADMI') END
IF NOT EXISTS(SELECT * FROM nexco_usuarios WHERE codigo_usuario='NEXADMI') BEGIN INSERT INTO nexco_usuarios(contra,correo,creacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,password_token,codigo_usuario,fecha_nacimiento,inicio_inactividad,fin_inactividad,id_tipo_documento,numero_documento,id_cargo) VALUES('$2a$10$Nlz1ECsmJ4r/CBiMPmFYr.guiQ0wO2iR0f6tK94aSFg5HmWiC6nYa','admin@admin.com',GETDATE(),'Pilar','Maritza','Llantoy','Sanchez',NULL,'NEXADMI','2000-01-28','2000-01-28','2000-01-28',1,78945612,1) END


IF NOT EXISTS(SELECT * FROM nexco_perfiles WHERE nombre_perfil = 'ADMIN') BEGIN INSERT INTO nexco_perfiles ( nombre_perfil) VALUES ('ADMIN')END
IF NOT EXISTS(SELECT * FROM nexco_perfiles WHERE nombre_perfil = 'USER') BEGIN INSERT INTO nexco_perfiles ( nombre_perfil) VALUES ('USER') END
IF NOT EXISTS(SELECT * FROM nexco_perfiles WHERE nombre_perfil = 'RESPONSABLE') BEGIN INSERT INTO nexco_perfiles ( nombre_perfil) VALUES ('RESPONSABLE') END

-- Add views to the database
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Usuarios') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Usuarios','/admin/users',1,'Administración','Usuarios','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Roles') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Roles','/profile/roles',1,'Administración','Roles','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cargos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cargos','/admin/cargos',1,'Administración','Cargos','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuadro Mando Jobs') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuadro Mando Jobs','/admin/controlPanelJobs',1,'Administración','Cuadro Mando Jobs','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuadro Mando Intergrupo') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuadro Mando Intergrupo','/admin/controlPanel',1,'Administración','Cuadro Mando Intergrupo','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Logs') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Logs','/admin/audit',1,'Administración','Log','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Plantilla Banco') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Plantilla Banco','/bank/templateBank',1,'Intergrupo','Plantilla de Carga','Banco') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Plantilla Filiales') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Plantilla Filiales','/bank/subsidiariesTemplate',1,'Intergrupo','Plantilla de Carga','Filiales') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Contingentes Plantilla') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Contingentes Plantilla','/reports/contingentes',1,'Intergrupo','Contingentes','Reporte Contingentes') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Contingentes Contratos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Contingentes Contratos','/reports/contingentesAvalType',1,'Intergrupo','Contingentes','Contingentes Contratos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver RP21') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver RP21','/reports/rp21',1,'Intergrupo','RP21','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver GPS') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver GPS','/bank/gpsreport',1,'Intergrupo','Comercializadora','GPS') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Conciliación Comer') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Conciliación Comer','/reports/conciliacionComer',1,'Intergrupo','Comercializadora','Conciliación Comer') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Base Fiscal') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Base Fiscal','/bank/taxBase',1,'Intergrupo','Base Fiscal','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver SICC') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver SICC','/information/sicc',1,'Intergrupo','SICC','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver MIS - Depositos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver MIS - Depositos','/information/mis',1,'Intergrupo','MIS - Depositos','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo - Query') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo - Query','/reports/reconciliationIntV1',1,'Intergrupo','Intergrupo - Query','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo Banco - Filiales') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo Banco - Filiales','/reports/reconciliationIntV1Fil',1,'Intergrupo','Intergrupo Banco - Filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo 1 Banco') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo 1 Banco','/reports/intergroup1',1,'Intergrupo','Intergrupo','Intergrupo V1 Banco') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Reclasificación Intergrupo V2') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Reclasificación Intergrupo V2','/reports/intergroup1',1,'Intergrupo','Intergrupo','Reclasificación Intergrupo V2') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo 2 Banco') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo 2 Banco','/reports/intergroup2',1,'Intergrupo','Intergrupo','Intergrupo V2 Banco') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo 3 Banco') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo 3 Banco','/reports/intergroup3',1,'Intergrupo','Intergrupo','Intergrupo V3 Banco') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo Filiales') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo Filiales','/bank/intergrupoSubsidiaries',1,'Intergrupo','Intergrupo','Intergrupo Filiales') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Descargable Intergrupo') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Descargable Intergrupo','/reports/intergroupVersions',1,'Intergrupo','Intergrupo','Descargable Intergrupo') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuenta Responsable') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuenta Responsable','/parametric/responsibleAccount',1,'Intergrupo','Paramétricas','Cuenta Responsable') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Banco Garante') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Banco Garante','/parametric/garantBank',1,'Intergrupo','Paramétricas','Banco Garante') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Histórico de terceros') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Histórico de terceros','/parametric/third',1,'Intergrupo','Paramétricas','Terceros') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Sociedades YNTP') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Sociedades YNTP','/parametric/yntp',1,'Intergrupo','Paramétricas','Sociedades YNTP') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Histórico de paises') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Histórico de paises','/parametric/country',1,'Intergrupo','Paramétricas','Paises') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cruce Filiales') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cruce Filiales','/parametric/subsidiaries',1,'Intergrupo','Paramétricas','Filiales') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Operación y Riesgo de Cuentas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Operación y Riesgo de Cuentas','/parametric/operationAccount',1,'Intergrupo','Paramétricas','Operación y Riesgo') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Tipos de aval') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Tipos de aval','/parametric/avalType',1,'Intergrupo','Paramétricas','Tipos de aval') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Histórico de Contratos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Histórico de Contratos','/parametric/contract',1,'Intergrupo','Paramétricas','Contratos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Transformación de Divisas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Transformación de Divisas','/parametric/currency',1,'Intergrupo','Paramétricas','Transformación de Divisas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuentas Neocon') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuentas Neocon','/parametric/neocon',1,'Intergrupo','Paramétricas','Cuentas Neocon') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Producto y Provisión') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Producto y Provisión','/parametric/provisions',1,'Intergrupo','Paramétricas','Producto y Provisión') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Indicadores Intergrupo') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Indicadores Intergrupo','/parametric/indicators',1,'Intergrupo','Paramétricas','Indicadores Intergrupo') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Metodología Comercializadora') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Metodología Comercializadora','/parametric/comerParametric',1,'Intergrupo','Paramétricas','Metodología Comercializadora') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Vertical De Saldos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Vertical De Saldos','/reports/ifrs9Report',1,'Conciliación IFRS9','Cuadre General','Cuadre Inicial') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Ajuste primera vez') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Ajuste primera vez','/ifrs/firstadjustment',1,'Conciliación IFRS9','Cambios de segmento','Ajustes Iniciales') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Perdida incurrida') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Perdida incurrida','/ifrs/incurredloss',1,'Conciliación IFRS9','Cambios de segmento','Perdida incurrida') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Riesgos de mercado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Riesgos de mercado','/ifrs/Risk',1,'Conciliación IFRS9','Riesgos de mercado','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Diferencias Conciliación automática') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Diferencias Conciliación automática','/ifrs/descontabilizacion',1,'Conciliación IFRS9','Conciliacion','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver R&S Conciliacion') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver R&S Conciliacion','/ifrs/repo',1,'Conciliación IFRS9','Paramétricas','R&S Conciliacion') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Query') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Query','/parametric/query',1,'Informacionales','Local','Query') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF','/ifrs/Eeff',1,'Informacionales','Neocon','EEFF Neocon') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Tipo de Entidad') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Tipo de Entidad','/parametric/typeEntity',1,'Intergrupo','Paramétricas','Tipo Entidad') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cambio Valor Divisa') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cambio Valor Divisa','/parametric/changeCurrency',1,'Informacionales','Local','Cambio Valor Divisa') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Historico Cambio Cuentas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Historico Cambio Cuentas','/ifrs/changeAccountQuery',1,'Informacionales','Local','Historico Cambio Cuentas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Manuales (ANEXO8 - SICC)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Manuales (ANEXO8 - SICC)','/ifrs/manuals',1,'IFRS9','Manuales (ANEXO8 - SICC)','NA') END
--IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuadro Mando IFRS9') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuadro Mando IFRS9','/admin/controlPanelIfrs',1,'Administración','Cuadro Mando IFRS9','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Rechazos (Creación Cuentas/Cambios Segementos)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Rechazos (Creación Cuentas/Cambios Segementos)','/ifrs/rejectionsCc',1,'Creación de cuentas','Plan 00','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Identificación Cuenta') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Identificación Cuenta','/ifrs/rejectIdP1',1,'Creación de cuentas','Paramétricas','Identificación Cuentas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Identificación Rechazos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Identificación Rechazos','/ifrs/rejectIdP2',1,'Creación de cuentas','Paramétricas','Identificación Rechazos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Control Contable') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Control Contable','/ifrs/accountControl',1,'Creación de cuentas','Paramétricas','Control Contable') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Equivalencias') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Equivalencias','/ifrs/equivalences',1,'Creación de cuentas','Paramétricas','Equivalencias') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas (Gestión)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas (Gestión)','/ifrs/accountCreation',1,'Creación de cuentas','Creación de cuentas','N/A') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas (Consolidación)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas (Consolidación)','/ifrs/accountCreation',1,'Creación de cuentas','Creación de cuentas','N/A') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas (Control Contable)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas (Control Contable)','/ifrs/accountCreation',1,'Creación de cuentas','Creación de cuentas','N/A') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas (General)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas (General)','/ifrs/accountCreation',1,'Creación de cuentas','Creación de cuentas','N/A') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Plano Ristras') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Plano Ristras','/ifrs/planeRistras',1,'Creación de cuentas','Plantillas Host','N/A') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Contabilización Riesgos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Contabilización Riesgos','/ifrs/riskAccount',1,'IFRS9','Riesgos','Contabilización Riesgos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Riesgos Cargue Fichero') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Riesgos Cargue Fichero','/ifrs/riskAccountLoad',1,'IFRS9','Riesgos','Cargue Fichero') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Conciliación RYS') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Conciliación RYS','/ifrs/rysConcil',1,'IFRS9','Ajuste Riesgos','N/A') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica RYS') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica RYS','/ifrs/rysParametric',1,'IFRS9','Parametricas','R&S Conciliacion') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Ajustes Homogeneizacion') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Ajustes Homogeneizacion','/ifrs/adjustmentsHom',1,'IFRS9','IFRS9','Ajustes Homogeneizacion') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Anexo 8 Cupos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Anexo 8 Cupos','/ifrs/anexo',1,'IFRS9','Anexo 8 Cupos','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuadre Query EEFF') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuadre Query EEFF','/ifrs/valQueryEeff',1,'IFRS9','Cuadre General','Cuadre Query EEFF') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Validación Segmentos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Validación Segmentos','/ifrs/segments',1,'IFRS9','Cambios de segmento','Validación Segmentos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Ajuste Segmentos Rechazos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Ajuste Segmentos Rechazos','/ifrs/segmentsRisk',1,'IFRS9','Cambios de segmento','Ajuste Segmentos Rechazos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Descontabilización Nivel 15') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Descontabilización Nivel 15','/ifrs/desconnv15',1,'IFRS9','Entradas IFRS9','Descontabilización Nivel 15') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Contabilidad Nivel 15') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Contabilidad Nivel 15','/ifrs/connv15',1,'IFRS9','Entradas IFRS9','Contabilidad Nivel 15') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Informe Nivel 15') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Informe Nivel 15','/ifrs/informenv15',1,'IFRS9','Entradas IFRS9','Informe Nivel 15') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Rechazos Descontabilización') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Rechazos Descontabilización','/parametric/rechazosDescontabilizacion',1,'IFRS9','Entradas IFRS9','Rechazos Descontabilización') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Conciliación IFRS9') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Conciliación IFRS9','/ifrs9/concilScopeIFRS9',1,'IFRS9','Conciliación SCOPE IFRS9','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Fichero Descontabilización') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Fichero Descontabilización','/reports/descontabilizacionReport',1,'IFRS9','Fichero Descontabilización','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Archivos Descontabilización Host') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Archivos Descontabilización Host','/ifrs9/desconValidation',1,'IFRS9','Validación Descontabilización','Archivos Descontabilización Host') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Validación Descontabilización') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Validación Descontabilización','/ifrs9/desconValConcil',1,'IFRS9','Validación Descontabilización','Conciliación Descontabilización') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Validación Información IFRS9') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Validación Información IFRS9','/ifrs9/valIFRS9',1,'IFRS9','Validación IFRS9','Validación Información IFRS9') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Plantillas Neocon') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Plantillas Neocon','/ifrs9/plainIFRS9',1,'IFRS9','Plantillas Neocon','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametría Contingentes Anexo 8') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametría Contingentes Anexo 8','/ifrs9/quotas',1,'IFRS9','Paramétricas','Parametría Contingentes Anexo 8') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuentas Genéricas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuentas Genéricas','/parametric/genericAccount',1,'IFRS9','Paramétricas','Cuentas Genéricas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Contrapartida y Contratos Genéricos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Contrapartida y Contratos Genéricos','/parametric/counterpartyGenericContracts',1,'IFRS9','Paramétricas','Contrapartida y Contratos Genéricos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Histórico de cuentas IFRS9') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Histórico de cuentas IFRS9','/parametric/accountHistoryIFRS9',1,'IFRS9','Paramétricas','Histórico de cuentas IFRS9') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuenta y subproductos locales') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuenta y subproductos locales','/parametric/accountAndByProduct',1,'IFRS9','Paramétricas','Cuenta y subproductos locales') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Genéricas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Genéricas','/parametric/accountAndByProduct',1,'IFRS9','Paramétricas','Genéricas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Árbol de decisión de segmento') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Árbol de decisión de segmento','/parametric/segmentDecisionTree',1,'IFRS9','Paramétricas','Árbol de decisión de segmento') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver CIIU') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver CIIU','/parametric/ciiu',1,'IFRS9','Paramétricas','CIIU') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Centros de Oficinas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Centros de Oficinas','/ifrs/center',1,'IFRS9','Paramétricas','Centros de Oficinas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Tipos Plantillas España') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Tipos Plantillas España','/parametric/typeTemplate',1,'IFRS9','Paramétricas','Tipos Plantillas España') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Provisión general de interés') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Provisión general de interés','/ifrs9/generalInterestProvision',1,'Provisiones','Circular 22','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Calculo 1%') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Calculo 1%','/ifrs9/onePercent',1,'Provisiones','Calculo 1%','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Fechas Calculo 1%') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Fechas Calculo 1%','/information/calendarDates',1,'Informacionales','Local','Fechas Calculo 1%') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Neocon') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Neocon','/ifrs/Eeff',1,'Informacionales','Neocon','EEFF Neocon') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cuadre Contable Motor CodNeocon') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cuadre Contable Motor CodNeocon','/ifrs/fitDifferences',1,'Conciliación IFRS9','Cuadre Contable Motor CodNeocon','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver PyG') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver PyG','/parametric/pyg',1,'Conciliación IFRS9','Paramétricas','PYG') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Histórico PYG & Impuesto') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Histórico PYG & Impuesto','/ifrs9/historicPyg',1,'Impuesto','NA','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Consolidado Fiduciaria') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Consolidado Fiduciaria','/eeffConsolidated/filiales',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Consolidado Valores') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Consolidado Valores','/eeffConsolidated/valores',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametria EEFF Consolidado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametria EEFF Consolidado','/eeffConsolidated/parametricsConsolidated',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Verificacion Filiales') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Verificacion Filiales','/eeffConsolidated/SubsidiaryVerification',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Consolidado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Consolidado','/eeffConsolidated/SubsidiaryVerification',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Reglas DQ') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Reglas DQ','/dataquality/reglas dq',1,'Reglas DQ','NA','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Firmas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Firmas','/parametric/signature',1,'Cuentas Por Cobrar','Paramétricas','Firmas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Terceros (CC)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Terceros (CC)','/parametric/thirdsCc',1,'Cuentas Por Cobrar','Paramétricas','Terceros') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Informe Cuentas Por Cobrar') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Informe Cuentas Por Cobrar','/parametric/collectionAccount',1,'Cuentas Por Cobrar','Informe','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Cuentas por Cobrar') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Cuentas por Cobrar','/parametric/collectionAccount',1,'Cuentas Por Cobrar','Paramétricas','Cuentas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Moneda') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Moneda','/parametric/mda',1,'NIC34','Paramétricas','Moneda') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica NIC34 Consolidado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica NIC34 Consolidado','/parametric/nic34',1,'NIC34','Paramétricas','NIC34') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica NIC34 General') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica NIC34 General','/parametric/nic34',1,'NIC34','Paramétricas','NIC34') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Fechas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Fechas','/parametric/fechas',1,'NIC34','Paramétricas','Fechas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Reporte NIC34') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Reporte NIC34','/reportNIC34/nic34',1,'NIC34','Reporte NIC34','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Consolidado Banco') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Consolidado Banco','/eeffConsolidated/filialesBanco',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Neocon 60') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Neocon 60','/information/neocon60',1,'Informacionales','Local','Neocon 60') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica EEFF Consolidado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica EEFF Consolidado','/eeffConsolidated/parametricsConsolidated',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF NIC34 Balance') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF NIC34 Balance','/reportNIC34/nic34Balance',1,'NIC34','EEFF','Balance') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF NIC34 PYG') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF NIC34 PYG','/reportNIC34/nic34Pyg',1,'NIC34','EEFF','PYG') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Informe Balance y PYG') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Informe Balance y PYG','/parametric/informe',1,'NIC34','Parametricas','Informe Balance y PYG') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Informe Notas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Informe Notas','/parametric/informeNotas',1,'NIC34','Parametricas','Informe Notas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF NIC34 Notas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF NIC34 Notas','/reportNIC34/nic34Notas',1,'NIC34','EEFF','Notas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Intergrupo Eliminaciones') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Intergrupo Eliminaciones','/eeffConsolidated/IntergrupoEliminaciones',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Intergrupo Eliminaciones Detalle') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Intergrupo Eliminaciones Detalle','/eeffConsolidated/IntergrupoEliminacionesDetalle',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Patrimoniales Fiduciaria') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Patrimoniales Fiduciaria','/eeffConsolidated/EeffPatrimoniales',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Patrimoniales Valores') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Patrimoniales Valores','/eeffConsolidated/EeffPatrimonialesValores',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Patrimoniales Asiento') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Patrimoniales Asiento','/eeffConsolidated/EeffPatrimonialesAsiento',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Intergrupo Verificacion Eliminaciones') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Intergrupo Verificacion Eliminaciones','/eeffConsolidated/VerificacionEliminaciones',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Naturaleza Cuentas') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Naturaleza Cuentas','/parametric/accountBanco',1,'Intergrupo','Parametricas','Naturaleza Cuentas') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas Otros (General)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas Otros (General)','/ifrs/accountCreationOther',1,'Creación de Cuentas','Otras Cuentas','Crear') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas Otros (Control Contable)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas Otros (Control Contable)','/ifrs/accountCreationOther',1,'Creación de Cuentas','Otras Cuentas','Crear') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas Otros (Consolidación)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas Otros (Consolidación)','/ifrs/accountCreationOther',1,'Creación de Cuentas','Otras Cuentas','Crear') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas Otros (Gestión)') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas Otros (Gestión)','/ifrs/accountCreationOther',1,'Creación de Cuentas','Otras Cuentas','Crear') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Creación de Cuentas Otros Planos') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Creación de Cuentas Otros Planos','/ifrs/accountCreationOtherPlane',1,'Creación de Cuentas','Otras Cuentas','Planos') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver EEFF Eliminaciones Ver PT') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver EEFF Eliminaciones Ver PT','/eeffConsolidated/patrimonialesVerPT',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Ajustes Minimos EEFF Consolidado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Ajustes Minimos EEFF Consolidado','/eeffConsolidated/parametricsAjustesMinimos',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Ajustes Mayores EEFF Consolidado') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Ajustes Mayores EEFF Consolidado','/eeffConsolidated/parametricsAjustesMayores',1,'EEFF Consolidado','EEFF filiales','NA') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Anexo 8 FINREP') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Anexo 8 FINREP','/reports/anexo8finrep',1,'Informacionales','Local','Anexo8 FINREP') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Parametrica Base ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Parametrica Base ICRV','/briefcase/baseicrv',1,'Portafolio','Parametricas','Base ICRV') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Precio ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Precio ICRV','/briefcase/precioicrv',1,'Portafolio','Parametricas','Precio ICRV') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Contactos ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Contactos ICRV','/briefcase/precioicrv',1,'Portafolio','Parametricas','Precio ICRV') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Cálculo ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Cálculo ICRV','/briefcase/calculoicrv',1,'Portafolio','ICRV','Cálculo') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver PDU ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver PDU ICRV','/briefcase/pduicrv',1,'Portafolio','Parametricas','PDU') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Bal Valores ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Bal Valores ICRV','/briefcase/balvaloresicrv',1,'Portafolio','Parametricas','Bal Valores') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Valores ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Valores ICRV','/briefcase/valoresicrv',1,'Portafolio','ICRV','Valores') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Bal Fiduciaria ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Bal Fiduciaria ICRV','/briefcase/balfiduciariaicrv',1,'Portafolio','Parametricas','Bal Fiduciaria') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Fiduciaria ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Fiduciaria ICRV','/briefcase/fiduciariaicrv',1,'Portafolio','Parametricas','Fiduciaria') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Nivel Jerarquia ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Nivel Jerarquia ICRV','/briefcase/niveljerarquiaicrv',1,'Portafolio','ICRV','Nivel Jerarquia') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver F351 ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver F351 ICRV','/briefcase/f351icrv',1,'Portafolio','ICRV','F351') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Reporte ICRV') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Reporte ICRV','/briefcase/icrv',1,'Portafolio','ICRV','Reporte') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Venta En Corto ICRF') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Venta En Corto ICRF','/briefcase/ventasencortoicrf',1,'Portafolio','ICRF','Ventas En Corto') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver UVR ICRF') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver UVR ICRF','/briefcase/uvricrf',1,'Portafolio','ICRF','UVR') END
IF NOT EXISTS(SELECT * FROM nexco_vistas WHERE nombre = 'Ver Países') BEGIN INSERT INTO nexco_vistas (nombre, ruta, unica,menu_principal,sub_menu_p1,sub_menu_p2) VALUES ('Ver Países','/parametry/countries',1,'Parametría','Parametros Generales','Países') END

IF NOT EXISTS(SELECT * FROM nexco_parametros_pyg WHERE id_parametros_pyg = 1) BEGIN INSERT INTO nexco_parametros_pyg (aplica_reversion) VALUES (0) END


-- Add JOBS
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 1) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (1,'GOF Base Fiscal',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 2) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (2,'HADT140',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 3) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (3,'Query',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 4) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (4,'SICC',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 5) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (5,'Depositos',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 6) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (6,'CONDETARI',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 7) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (7,'Desconnv15',0) END
IF NOT EXISTS(SELECT * FROM nexco_cuadro_mando_jobs WHERE id_job = 8) BEGIN INSERT INTO nexco_cuadro_mando_jobs (id_job, nombre, estado) VALUES (8,'Calculo 1%',0) END

IF NOT EXISTS(SELECT * FROM nexco_user_rol WHERE id_usuario = 1 AND id_perfil=1) BEGIN INSERT INTO nexco_user_rol (id_perfil,id_usuario) VALUES (1,1) END
-- IF NOT EXISTS(SELECT * FROM nexco_rol_vista AS nrv, nexco_vistas AS nv WHERE nrv.id_perfil = 1 AND nv.nombre = 'Ver Cuadro Mando Intergrupo' AND nv.id_vista = nrv.id_vista) BEGIN INSERT INTO nexco_rol_vista (id_perfil,id_vista) VALUES (1,4) END
IF NOT EXISTS(SELECT * FROM nexco_rol_vista AS nrv, nexco_vistas AS nv WHERE nrv.id_perfil = 1 AND nv.nombre = 'Ver Roles' AND nv.id_vista = nrv.id_vista) BEGIN INSERT INTO nexco_rol_vista (id_perfil,id_vista) VALUES (1,4) END
IF NOT EXISTS(SELECT * FROM nexco_operacion_riesgo WHERE cuenta_local='-') BEGIN INSERT INTO nexco_operacion_riesgo (cuenta_local) VALUES ('-') END

-- Datos predeterminados para Contrapartida y Contratos genericos
IF NOT EXISTS(SELECT NULL FROM nexco_counterparty_generic_contracts) BEGIN INSERT INTO nexco_counterparty_generic_contracts (concepto, cuenta, contrato, fuente_informacion,saldo) VALUES (' 2-DESCONT_DESC_CONCIL','196095999','001302039000000101', 'Diferencias conciliación',-1), ('1-DESCONT_CTAS_MANUALES','196095999','001302039000000102','Manuales (Anexos 8)',-1), ('1-DESCONTAB_PROV_GENERAL','196095999','001302039000000103','Provisión general Capitales',-1), ('1-DESCONTAB_PROV_GENERICA_INTERESES','196095999','001302039000000103','Provisión general Intereses',-1), ('2-DESCONT_SIN_SCOPE','196095999','001302039000000104','Rechazos descontabilización',1), ('1-DESCONT_CTAS_RENTA_FIJA','196095999','001302039000000105','Anexos 8 - Renta fija',-1) END

-- Datos predeterminados para Arbol Decisión Segmentos FINREP
IF NOT EXISTS(SELECT NULL FROM nexco_arbol_decision_segmento) BEGIN INSERT INTO nexco_arbol_decision_segmento (codigo_ifrs9, descripcion_sectorizacion, corasu_op, corasu, sub_corasu_op, sub_corasu, ciiu_op, ciiu, numero_empleados_op, numero_empleados, total_activos_op, total_activos, total_ventas_op, total_ventas, verificacion_contratos, otros_criterios) VALUES ('001','Bancos Centrales','=','G','=','00','','','','','','','','','',''), ('002','Administraciones Públicas','=','G','<>','00','','','','','','','','','',''), ('003','Entidades de Crédito','=','M','IN','20,21,22,23,24,25,26','=','6412','','','','','','','',''), ('004','Otras instituciones financieras','=','M','IN','21,22,23,24,25,26','IN','CIIU','','','','','','','',''), ('005','Sociedades no Financieras Mayoristas','=','M','IN','00,01,10,12','','','>','250','>','50000000','>','43000000','','Que cumpla los criterios de sociedad no financiera'), ('005','Sociedades no Financieras Mayoristas','=','M','=','20','<>','6412','>','250','>','50000000','>','43000000','','Que cumpla los criterios de sociedad no financiera'), ('005','Sociedades no Financieras Mayoristas','=','M','IN','21,22,23,24,25,26','NOT IN','CIIU','>','250','>','50000000','>','43000000','','Que cumpla los criterios de sociedad no financiera'), ('006','Sociedades no Financieras Minorista','=','M','IN','00,01,10,12','','','','','','','','','','Sociedades no Financieras no Mayoristas'), ('006','Sociedades no Financieras Minorista','=','M','=','20','<>','6412','','','','','','','','Sociedades no Financieras no Mayoristas'), ('006','Sociedades no Financieras Minorista','=','M','IN','21,22,23,24,25,26','NOT IN','CIIU','','','','','','','','Sociedades no Financieras no Mayoristas'), ('007','Hogares','=','F','IN','00,10','=','10','','','','','','','',''), ('007','Hogares','=','F','','','','','','','','','','','Tiene producto(s) de Libranza',''), ('007','Hogares','=','F','','','','','','','','','','','Tiene producto(s) de Adelanto de Nómina',''), ('007','Hogares','=','F','=','17','','','','','','','','','',''), ('008','Autónomos','=','F','','','','','','','','','','','','No incluidas en hogares') END

